import type { NextPage } from 'next'
import Head from 'next/head'
import Logo from 'components/Logo'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Milinkov Nikita | Presonal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo />
    </>
  )
}

export default Home