import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from 'components/Layout'
import Hero from 'components/Hero'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Milinkov Nikita | Presonal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
      </Layout>
    </>
  )
}

export default Home